version: '2'
services:
  web:
    build: . 
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: node bin/www
    depends_on:
    - bdd
  bdd:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./db:/data/db
