version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: pm2 start --watch --no-daemon /usr/src/app/bin/www
    depends_on:
    - bdd
  bdd:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    command: --smallfiles
volumes:
  mongodata:
